sample_products = [
    {
        "title": "Men Solid Polo Neck Pure Cotton White T-Shirt",
        "description": "Premium solid white polo neck t-shirt in pure cotton fabric.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/b/s/p/-original-imagzwrsmryt7kzt.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/b/s/p/-original-imagzwrsmryt7kzt.jpeg?q=70",
        "originalPrice": 1799,
        "price": 809,
        "platform": "Flipkart",   
        "affiliate_link": "https://fktr.in/1sCCc4w",
        "category": "tshirts",
        "subcategory": "tshirts",
        "gender": "men",
        "occasion": ["casual", "sports"],
        "season": ["summer", "spring"],
        "tags": ["polo", "classic", "cotton"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42"},
    },
    {
        "title": "Men Henley Neck Black T-Shirt",
        "description": "Stylish black Henley neck t-shirt, perfect for casual outings.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/z/1/b/m-askporob73523-ausk-original-imagq22gygupmzz2.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/t-shirt/z/1/b/m-askporob73523-ausk-original-imagq22gygupmzz2.jpeg?q=70",
        "originalPrice": 1299,
        "price": 599,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/2aDDe4w",
        "category": "tshirts",
        "subcategory": "tshirts",
        "gender": "men",
        "occasion": ["casual"],
        "season": ["summer", "spring"],
        "tags": ["henley", "black", "slim-fit"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42", "XL": "42-44"},
    },
    {
        "title": "Men Classic Denim Shirt",
        "description": "Classic blue denim shirt with dual chest pockets and durable fabric.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/i/v/t/m-ud-denim-01-uc-box-original-imaghyfhkzex2ezy.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/i/v/t/m-ud-denim-01-uc-box-original-imaghyfhkzex2ezy.jpeg?q=70",
        "originalPrice": 2499,
        "price": 1199,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/3bEEe4w",
        "category": "shirts",
        "subcategory": "shirts",
        "gender": "men",
        "occasion": ["casual", "evening"],
        "season": ["winter", "autumn", "spring"],
        "tags": ["denim", "blue", "rugged"],
        "size_chart": {"M": "38-40", "L": "40-42", "XL": "42-44"},
    },
    {
        "title": "Men Checked Casual Shirt",
        "description": "Trendy checked casual shirt for a smart-casual look.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/g/d/y/m-db-1024-14-combraid-original-imagm9gzmhhwyuzn.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/g/d/y/m-db-1024-14-combraid-original-imagm9gzmhhwyuzn.jpeg?q=70",
        "originalPrice": 1999,
        "price": 999,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/4cFFe4w",
        "category": "shirts",
        "subcategory": "shirts",
        "gender": "men",
        "occasion": ["casual", "office-casual"],
        "season": ["all"],
        "tags": ["checked", "cotton", "smart-casual"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42"},
    },
    {
        "title": "Men Slim Fit Cotton Shirt",
        "description": "Stylish slim-fit cotton shirt in plain white, perfect for multi-layering.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/h/g/i/xxl-kcse-s-15-den-wht-killer-original-imagzhg9yphdwhgu.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/h/g/i/xxl-kcse-s-15-den-wht-killer-original-imagzhg9yphdwhgu.jpeg?q=70",
        "originalPrice": 1899,
        "price": 899,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/5dGGe4w",
        "category": "shirts",
        "subcategory": "shirts",
        "gender": "men",
        "occasion": ["casual", "formal"],
        "season": ["summer", "spring"],
        "tags": ["white", "slim-fit", "cotton"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42", "XL": "42-44"},
    },
    {
        "title": "Men Arrow Formal Cotton Shirt",
        "description": "Premium formal cotton shirt by Arrow, tailored for professional business wear.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/r/t/7/38-9006612-arrow-original-imaggf2hhqgyh84j.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/r/t/7/38-9006612-arrow-original-imaggf2hhqgyh84j.jpeg?q=70",
        "originalPrice": 2999,
        "price": 1899,
        "platform": "Amazon",
        "affiliate_link": "https://example.com/product/arrow-shirt",
        "category": "shirts",
        "subcategory": "shirts",
        "gender": "men",
        "occasion": ["formal", "business"],
        "season": ["all"],
        "tags": ["arrow", "formal", "premium"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42", "XL": "42-44"},
    },
    {
        "title": "Women Yellow Floral Summer Maxi Dress",
        "description": "Flowing yellow maxi dress with beautiful floral print, perfect for summer outings.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/z/d/3/m-3037-yell-siril-original-imaghfnydphggygz.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/z/d/3/m-3037-yell-siril-original-imaghfnydphggygz.jpeg?q=70",
        "originalPrice": 1999,
        "price": 899,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/6eHHe4w",
        "category": "dresses",
        "subcategory": "dresses",
        "gender": "women",
        "occasion": ["casual", "outing", "beach"],
        "season": ["summer"],
        "tags": ["floral", "maxi", "yellow", "summer"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
    {
        "title": "Women Georgette A-line Dress",
        "description": "Elegant georgette A-line dress in maroon, suitable for evening gatherings.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/t/h/g/m-aa-0120-d-dress-ananya-creation-original-imagznzzkuf4y7hu.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/dress/t/h/g/m-aa-0120-d-dress-ananya-creation-original-imagznzzkuf4y7hu.jpeg?q=70",
        "originalPrice": 2499,
        "price": 1299,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/7fIIe4w",
        "category": "dresses",
        "subcategory": "dresses",
        "gender": "women",
        "occasion": ["party", "evening"],
        "season": ["all"],
        "tags": ["georgette", "a-line", "maroon"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38", "XL": "38-40"},
    },
    {
        "title": "Women Embroidered Anarkali Kurta Set",
        "description": "Traditional cotton Anarkali kurta set with exquisite embroidery details.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/v/s/4/m-22fe07-anubhutee-original-imaghg7szjqyhsgk.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/ethnic-set/v/s/4/m-22fe07-anubhutee-original-imaghg7szjqyhsgk.jpeg?q=70",
        "originalPrice": 3999,
        "price": 1899,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/8gJJe4w",
        "category": "kurtas",
        "subcategory": "kurtas",
        "gender": "women",
        "occasion": ["festive", "formal"],
        "season": ["all"],
        "tags": ["kurta", "anarkali", "festive", "traditional"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
    {
        "title": "Women Vasundhara Silk Blend Saree",
        "description": "Rich traditional silk blend saree with designer borders and zari work.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/sari/v/e/q/free-vasundhara-dharini-original-imagg9zvyhzncgy8.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/sari/v/e/q/free-vasundhara-dharini-original-imagg9zvyhzncgy8.jpeg?q=70",
        "originalPrice": 5999,
        "price": 2499,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/9hKKe4w",
        "category": "sarees",
        "subcategory": "sarees",
        "gender": "women",
        "occasion": ["festive", "party", "wedding"],
        "season": ["all"],
        "tags": ["saree", "silk-blend", "traditional"],
        "size_chart": {"free": "5.5m"},
    },
    {
        "title": "Women Casual Denim Jacket",
        "description": "Rugged and fashionable women's blue denim jacket with front pockets.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/jacket/i/y/l/xl-no-5463-jeans-jacket-shree-sharnam-creation-original-imaghs4w4jthq9yy.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/jacket/i/y/l/xl-no-5463-jeans-jacket-shree-sharnam-creation-original-imaghs4w4jthq9yy.jpeg?q=70",
        "originalPrice": 2499,
        "price": 1399,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/10iLLe4w",
        "category": "jackets",
        "subcategory": "jackets",
        "gender": "women",
        "occasion": ["casual", "outdoor"],
        "season": ["winter", "autumn"],
        "tags": ["denim", "jacket", "blue"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
    {
        "title": "Women Off-Shoulder Crop Top",
        "description": "Trendy yellow off-shoulder crop top for casual summer styling.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/top/h/r/e/m-top-347-yellow-juneberry-original-imagkhecmyczz3eh.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/top/h/r/e/m-top-347-yellow-juneberry-original-imagkhecmyczz3eh.jpeg?q=70",
        "originalPrice": 1199,
        "price": 549,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/11jMMe4w",
        "category": "tops",
        "subcategory": "tops",
        "gender": "women",
        "occasion": ["casual", "party"],
        "season": ["summer", "spring"],
        "tags": ["off-shoulder", "crop", "yellow"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
    {
        "title": "Women Levi's High Rise Jeans",
        "description": "Authentic Levi's high-rise skinny jeans in classic dark blue denim.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/r/o/p/30-18298-0955-levi-s-original-imagg2pbfg7b5gzb.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/jean/r/o/p/30-18298-0955-levi-s-original-imagg2pbfg7b5gzb.jpeg?q=70",
        "originalPrice": 2999,
        "price": 1999,
        "platform": "Amazon",
        "affiliate_link": "https://example.com/product/levis-jeans",
        "category": "jeans",
        "subcategory": "jeans",
        "gender": "women",
        "occasion": ["casual", "everyday"],
        "season": ["all"],
        "tags": ["jeans", "skinny", "levis"],
        "size_chart": {"S": "28", "M": "30", "L": "32"},
    },
    {
        "title": "Men Pantaloons Chino Shorts",
        "description": "Comfortable cotton chino shorts by Pantaloons, ideal for warm weather.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/short/w/s/4/32-205128001-pantaloons-original-imaghs4gzsnhkkyy.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/short/w/s/4/32-205128001-pantaloons-original-imaghs4gzsnhkkyy.jpeg?q=70",
        "originalPrice": 1499,
        "price": 799,
        "platform": "Flipkart",
        "affiliate_link": "https://fktr.in/12kNNe4w",
        "category": "shorts",
        "subcategory": "shorts",
        "gender": "men",
        "occasion": ["casual", "beach"],
        "season": ["summer"],
        "tags": ["shorts", "chino", "cotton"],
        "size_chart": {"S": "30", "M": "32", "L": "34"},
    },
    {
        "title": "Men Nike Revolution Running Shoes",
        "description": "Nike Revolution athletic running shoes with soft foam cushioning.",
        "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/c/w/o/6-da8535-001nike-6-nike-black-original-imagkfy2mghygwbh.jpeg?q=70",
        "image": "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/c/w/o/6-da8535-001nike-6-nike-black-original-imagkfy2mghygwbh.jpeg?q=70",
        "originalPrice": 3999,
        "price": 2499,
        "platform": "Amazon",
        "affiliate_link": "https://example.com/product/nike-shoes",
        "category": "shoes",
        "subcategory": "shoes",
        "gender": "men",
        "occasion": ["sports", "casual"],
        "season": ["all"],
        "tags": ["nike", "running", "shoes"],
        "size_chart": {"6": "UK 6", "7": "UK 7", "8": "UK 8", "9": "UK 9"},
    },
]
