sample_products = [
    {
        "title": "Men Solid Polo Neck Pure Cotton White T-Shirt",
        "description": "Men Solid Polo Neck Pure Cotton White T-Shirt",
        "image_url": "https://rukminim2.flixcart.com/image/1536/1536/xif0q/t-shirt/b/s/p/-original-imagzwrsmryt7kzt.jpeg?q=90",
        "image": "https://rukminim2.flixcart.com/image/1536/1536/xif0q/t-shirt/b/s/p/-original-imagzwrsmryt7kzt.jpeg?q=90",
        "originalPrice": 1799,
        "price": 809,
        "platform": "Myntra",   
        "affiliate_link": "https://fktr.in/1sCCc4w",
        "category": "T-shirts",
        "gender": "men",
        "occasion": ["casual"],
        "season": ["summer", "spring"],
        "tags": ["slim-fit", "classic", "cotton"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42"},
    },
    {
        "title": "Floral Summer Dress",
        "description": "Lightweight floral dress made for summer outings and brunches.",
        "image_url": "https://images.unsplash.com/photo-1595777707802-e176fc7f42b9?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1595777707802-e176fc7f42b9?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1899,
        "platform": "Ajio",
        "affiliate_link": "https://example.com/product/2",
        "category": "dresses",
        "gender": "women",
        "occasion": ["casual", "party"],
        "season": ["summer"],
        "tags": ["floral", "summer", "lightweight"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
    {
        "title": "Leather Bomber Jacket",
        "description": "A premium leather bomber jacket with a timeless silhouette.",
        "image_url": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop&auto=format&q=80",
        "badge": "SALE",
        "originalPrice": 6499,
        "price": 5499,
        "platform": "Amazon",
        "affiliate_link": "https://example.com/product/3",
        "category": "jackets",
        "gender": "men",
        "occasion": ["casual", "evening"],
        "season": ["winter", "autumn"],
        "tags": ["leather", "bomber", "outdoor"],
        "size_chart": {"M": "38-40", "L": "40-42", "XL": "42-44"},
    },
    {
        "title": "Off-Shoulder Top",
        "description": "A modern off-shoulder top that pairs well with denim and skirts.",
        "image_url": "https://images.unsplash.com/photo-1485872299829-c673f5194813?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1485872299829-c673f5194813?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1599,
        "platform": "Zalora",
        "affiliate_link": "https://example.com/product/4",
        "category": "tops",
        "gender": "women",
        "occasion": ["casual", "outing"],
        "season": ["summer", "spring"],
        "tags": ["off-shoulder", "trendy", "light"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
    {
        "title": "Blue Denim Jeans",
        "description": "Classic blue denim jeans with perfect fit and comfort.",
        "image_url": "https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1542272604-787c62d465d1?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1799,
        "platform": "Myntra",
        "affiliate_link": "https://example.com/product/5",
        "category": "jeans",
        "gender": "women",
        "occasion": ["casual", "everyday"],
        "season": ["all"],
        "tags": ["denim", "classic", "comfortable"],
        "size_chart": {"S": "26", "M": "28", "L": "30"},
    },
    {
        "title": "Oxford Button-Up Shirt",
        "description": "Premium oxford cloth button-up shirt for business or casual wear.",
        "image_url": "https://images.unsplash.com/photo-1596521529104-979a84b0b67b?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1596521529104-979a84b0b67b?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1999,
        "platform": "Amazon",
        "affiliate_link": "https://example.com/product/6",
        "category": "shirts",
        "gender": "men",
        "occasion": ["formal", "business"],
        "season": ["all"],
        "tags": ["oxford", "formal", "professional"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42", "XL": "42-44"},
    },
    {
        "title": "Elegant Black Blazer",
        "description": "Sophisticated black blazer perfect for formal events and office wear.",
        "image_url": "https://images.unsplash.com/photo-1539533057440-7814a9d790cc?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1539533057440-7814a9d790cc?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 3499,
        "platform": "Zalora",
        "affiliate_link": "https://example.com/product/7",
        "category": "jackets",
        "gender": "women",
        "occasion": ["formal", "business"],
        "season": ["all"],
        "tags": ["blazer", "elegant", "formal"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
    {
        "title": "Casual Chino Shorts",
        "description": "Comfortable chino shorts ideal for summer and casual outings.",
        "image_url": "https://images.unsplash.com/photo-1598033129519-c90900bc9de1?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1598033129519-c90900bc9de1?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1299,
        "platform": "Ajio",
        "affiliate_link": "https://example.com/product/8",
        "category": "shorts",
        "gender": "men",
        "occasion": ["casual", "outing"],
        "season": ["summer"],
        "tags": ["chino", "casual", "breathable"],
        "size_chart": {"S": "28-30", "M": "30-32", "L": "32-34"},
    },
    {
        "title": "Silk Blend Saree",
        "description": "Traditional silk blend saree with beautiful embroidery and elegant drape.",
        "image_url": "https://images.unsplash.com/photo-1606114863934-b9f36ce4d9f9?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1606114863934-b9f36ce4d9f9?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 4999,
        "platform": "Myntra",
        "affiliate_link": "https://example.com/product/9",
        "category": "sarees",
        "gender": "women",
        "occasion": ["formal", "party"],
        "season": ["all"],
        "tags": ["silk", "traditional", "embroidered"],
        "size_chart": {"free": "5.5m"},
    },
    {
        "title": "Polo T-Shirt",
        "description": "Classic polo t-shirt with collar, perfect for smart casual look.",
        "image_url": "https://images.unsplash.com/photo-1591028089180-8566532f552c?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1591028089180-8566532f552c?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 899,
        "platform": "Amazon",
        "affiliate_link": "https://example.com/product/10",
        "category": "tshirts",
        "gender": "men",
        "occasion": ["casual", "sports"],
        "season": ["summer"],
        "tags": ["polo", "casual", "cotton"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42", "XL": "42-44"},
    },
    {
        "title": "Maxi Skirt",
        "description": "Flowing maxi skirt with waist tie, suitable for casual and evening wear.",
        "image_url": "https://images.unsplash.com/photo-1583769404967-f70a3b3e5eda?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1583769404967-f70a3b3e5eda?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1599,
        "platform": "Zalora",
        "affiliate_link": "https://example.com/product/11",
        "category": "skirts",
        "gender": "women",
        "occasion": ["casual", "evening"],
        "season": ["summer", "spring"],
        "tags": ["maxi", "flowy", "casual"],
        "size_chart": {"S": "26", "M": "28", "L": "30"},
    },
    {
        "title": "Hoodie Sweatshirt",
        "description": "Warm and cozy hoodie sweatshirt perfect for cool weather.",
        "image_url": "https://images.unsplash.com/photo-1556821552-5f77f9f82a0a?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1556821552-5f77f9f82a0a?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1499,
        "platform": "Ajio",
        "affiliate_link": "https://example.com/product/12",
        "category": "hoodies",
        "gender": "men",
        "occasion": ["casual", "everyday"],
        "season": ["winter", "autumn"],
        "tags": ["hoodie", "warm", "comfortable"],
        "size_chart": {"S": "36-38", "M": "38-40", "L": "40-42", "XL": "42-44"},
    },
    {
        "title": "Crop Top",
        "description": "Trendy crop top that pairs beautifully with high-waisted bottoms.",
        "image_url": "https://images.unsplash.com/photo-1563693826-0ae4b7c5b5e1?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1563693826-0ae4b7c5b5e1?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 799,
        "platform": "Myntra",
        "affiliate_link": "https://example.com/product/13",
        "category": "tops",
        "gender": "women",
        "occasion": ["casual", "party"],
        "season": ["summer"],
        "tags": ["crop", "trendy", "modern"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
    {
        "title": "Formal Trousers",
        "description": "Well-tailored formal trousers in neutral colors for professional wear.",
        "image_url": "https://images.unsplash.com/photo-1473952147585-141821a92e2c?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1473952147585-141821a92e2c?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1699,
        "platform": "Amazon",
        "affiliate_link": "https://example.com/product/14",
        "category": "trousers",
        "gender": "men",
        "occasion": ["formal", "business"],
        "season": ["all"],
        "tags": ["formal", "professional", "tailored"],
        "size_chart": {"S": "28-30", "M": "30-32", "L": "32-34", "XL": "34-36"},
    },
    {
        "title": "Linen Summer Shirt",
        "description": "Breathable linen shirt ideal for hot summer days.",
        "image_url": "https://images.unsplash.com/photo-1600180897257-f27407a7bbbe?w=800&h=1000&fit=crop&auto=format&q=80",
        "image": "https://images.unsplash.com/photo-1600180897257-f27407a7bbbe?w=800&h=1000&fit=crop&auto=format&q=80",
        "price": 1399,
        "platform": "Zalora",
        "affiliate_link": "https://example.com/product/15",
        "category": "shirts",
        "gender": "women",
        "occasion": ["casual", "outing"],
        "season": ["summer"],
        "tags": ["linen", "breathable", "light"],
        "size_chart": {"S": "32-34", "M": "34-36", "L": "36-38"},
    },
]
